#server Port

server:
  port: 8082

#Context Path
  servlet:
    context-path: /hotelservice

#MySQL Config

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: root

#JPA Congig
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true